### ISSUE TITLE
WebDriver session Still active

### ISSUE THREAD

**Issue by zatchgordon** [F1LT3R/protractor-jasmine2-fail-whale#1]
First off, this is crazy helpful in letting me know when and why something is failing. My problem, however is that after the fail the session is still active so then I have to open up the WebDriver hub, refresh sessions, then delete the sessions. 
It's not a big deal but it would be super if fail whale did this automatically.

**Comment by F1LT3R** [comment]
Interesting, I'd like to help. Can you tell me more about opening up the WebDriver hub and refreshing/deleting?

This is not something I am familiar with, can you describe the steps you take in more detail?

**Comment by zatchgordon** [comment]
In the config file there's the exports.config = {};
inside there's the options for the seleniumAddress
by default it is "http://localhost:4444/wd/hub"
So it looks like
```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['path/to/file.js']
}
```
In the browser at the given addres "http://localhost:4444/wd/hub", as Protractor is running, there's a button with the name "refresh sessions". If that button is clicked, it will show tabs of each instance being run. For each tab there are the options "Take Screenshot  |  Delete Session  |  Load Script".

I use this place to delete any sessions that are stalling too much. Normally after a protractor instance is done running, the session goes away as well. In the case of an error the sessions stay around for longer or are never deleted automatically, so I delete them to help not slow down and to keep track of what I have running.

With fail-whale, when an error occurs, my console displays the whale, displays the camera, but does not close the browser currently being tested in, and if I go to the url 'http://localhost:4444/wd/hub' and click refresh sessions, all of the sessions are still running from the fails.

I hope this helps you in understanding what I am talking about

**Comment by F1LT3R** [comment]
Ok I think I found what you are talking about...

<img width="1435" alt="screen shot 2016-03-16 at 2 16 45 pm" src="https://cloud.githubusercontent.com/assets/1218446/13823838/c74748f4-eb81-11e5-8a08-75baa7b149b1.png">

I've actually not seen or used that before.

I will look into this. I'm assuming protractor is doing some cleanup internally which we can probably hook into from the failwhale reporter.

**Comment by zatchgordon** [comment]
Yes that is exactly what I'm talking about.
I'm pretty sure removing the session closes the browser in addition to removing the session. If it does do this when removing the session programmatically, the option to have the session removed on failure could be an option in the same way showStack or screenshot are boolean options: some people might like to inspect elements on a page after the failure to see why failures are happening.

**Comment by F1LT3R** [comment]
Ok I think I have that fixed.

Can you `npm install protractor-jasmine2-fail-whale` again and confirm that it exists for you?

BTW: You on OSX?

**Comment by zatchgordon** [comment]
The computer I was using was a windows10 computer but I was going to try it out on OSX tonight. I'll let you know how it goes with the update as well as on OSX.

**Comment by F1LT3R** [comment]
Sounds good. Thanks @zatchgordon

**Comment by F1LT3R** [comment]
Did you have any luck @zatchgordon?

**Comment by zatchgordon** [comment]
Whoops. I typed in this message and then never hit comment. 

I re-installed it on the Windows10 and installed it on OSX and happy to say it works on both. 
The only difference was the path to where the image is saved is a little different, but that's to be expected. If OSX was having problems saving any images I just ran protractor as sudo.

**Comment by F1LT3R** [comment]
Interesting. Thanks @zatchgordon.

In case it helps: I am not running `sudo` to save images/screenshots on OSX. I wonder if you may have installed Node, or one of your node packages using `sudo`, or you are trying to write to a directory outside of your repo.

You happy for me to go ahead and close this issue?

**Comment by zatchgordon** [comment]
Yeah I had the route to save the image outside of my home directory by accident. On windows i could use the ./screenshot notation to save it in the current folder wherever I was but it wasn't working on OSX so it save it elsewhere. Once I changed the save location to to correct location I ran it without sudo and it worked just fine.

**Comment by F1LT3R** [comment]
Great!

**Comment by F1LT3R** [comment]
Closing issue.
